window.RoutingMockData = (() => {
  const coreJurisdictions = ['Singapore', 'Hong Kong', 'India', 'Australia', 'Malaysia'];

  const topics = [
    'AI Regulation',
    'Privacy/Data Protection',
    'Judiciary Modernization',
    'Legal Tech Market Intelligence',
    'Legislative Development',
    'Precedent-Setting Judgment',
    'Citation Spike',
    'API/Data Licensing',
  ];

  const sourceRegistry = [
    { jurisdiction: 'Singapore', name: 'IMDA / AI Verify', category: 'AI regulation', sourceType: 'official', url: 'https://aiverifyfoundation.sg/' },
    { jurisdiction: 'Singapore', name: 'Singapore Law Watch', category: 'legal intelligence', sourceType: 'publisher', url: 'https://www.singaporelawwatch.sg/' },
    { jurisdiction: 'Hong Kong', name: 'Hong Kong Judiciary', category: 'judiciary modernization', sourceType: 'court', url: 'https://www.judiciary.hk/' },
    { jurisdiction: 'Hong Kong', name: 'PCPD Hong Kong', category: 'privacy/data protection', sourceType: 'regulator', url: 'https://www.pcpd.org.hk/' },
    { jurisdiction: 'Hong Kong', name: 'Hong Kong e-Legislation', category: 'API/data licensing', sourceType: 'official', url: 'https://www.elegislation.gov.hk/' },
    { jurisdiction: 'India', name: 'Ministry of Electronics and Information Technology', category: 'AI regulation', sourceType: 'government', url: 'https://www.meity.gov.in/' },
    { jurisdiction: 'India', name: 'Ministry of Law & Justice', category: 'legislative development', sourceType: 'government', url: 'https://lawmin.gov.in/' },
    { jurisdiction: 'India', name: 'Supreme Court of India', category: 'precedent-setting judgments', sourceType: 'court', url: 'https://www.sci.gov.in/' },
    { jurisdiction: 'India', name: 'eCourts Mission Mode Project', category: 'judiciary modernization', sourceType: 'court', url: 'https://ecourts.gov.in/' },
    { jurisdiction: 'Australia', name: 'OAIC / Federal Register', category: 'privacy and legislation', sourceType: 'regulator', url: 'https://www.oaic.gov.au/' },
    { jurisdiction: 'Australia', name: 'Federal Register of Legislation', category: 'legislative development', sourceType: 'official', url: 'https://www.legislation.gov.au/' },
    { jurisdiction: 'Australia', name: 'High Court of Australia', category: 'precedent-setting judgments', sourceType: 'court', url: 'https://www.hcourt.gov.au/' },
    { jurisdiction: 'Malaysia', name: 'Malaysian Bar', category: 'legal updates', sourceType: 'publisher', url: 'https://www.malaysianbar.org.my/' },
    { jurisdiction: 'Malaysia', name: 'Parliament of Malaysia', category: 'legislative development', sourceType: 'government', url: 'https://www.parlimen.gov.my/' },
    { jurisdiction: 'Malaysia', name: 'Personal Data Protection Department', category: 'privacy/data protection', sourceType: 'regulator', url: 'https://www.pdp.gov.my/' },
    { jurisdiction: 'Malaysia', name: 'Office of the Chief Registrar', category: 'judiciary modernization', sourceType: 'court', url: 'https://www.kehakiman.gov.my/' },
    { jurisdiction: 'Core APAC', name: 'Legal Tech Market Scan', category: 'legal tech market intelligence', sourceType: 'market intelligence', url: 'https://www.artificiallawyer.com/' },
    { jurisdiction: 'Core APAC', name: 'Market Intelligence Desk', category: 'API/data licensing', sourceType: 'market intelligence', url: 'https://www.lawnext.com/category/lawsites' },
  ];

  const departments = [
    {
      id: 'product',
      name: 'PAL (Practice Area Lead)',
      shortName: 'PAL',
      priorityTopics: {
        'AI Regulation': 95,
        'API/Data Licensing': 92,
        'Privacy/Data Protection': 78,
        'Judiciary Modernization': 72,
        'Legal Tech Market Intelligence': 82,
        'Legislative Development': 88,
        'Precedent-Setting Judgment': 82,
      },
      priorityJurisdictions: ['Singapore', 'India', 'Australia', 'Hong Kong'],
      frequency: 'Weekly',
      channel: 'Email',
      tone: 'Technical',
    },
    {
      id: 'legislation',
      name: 'Legislation Team',
      shortName: 'Legislation',
      priorityTopics: {
        'Legislative Development': 96,
        'AI Regulation': 90,
        'Privacy/Data Protection': 84,
        'Precedent-Setting Judgment': 66,
      },
      priorityJurisdictions: coreJurisdictions,
      frequency: 'Daily',
      channel: 'Email',
      tone: 'Operational',
    },
    {
      id: 'sales',
      name: 'SLT',
      shortName: 'SLT',
      priorityTopics: {
        'AI Regulation': 88,
        'Legal Tech Market Intelligence': 94,
        'API/Data Licensing': 78,
        'Privacy/Data Protection': 70,
      },
      priorityJurisdictions: ['Singapore', 'Hong Kong', 'Australia', 'India'],
      frequency: 'Weekly',
      channel: 'Email',
      tone: 'Executive',
    },
    {
      id: 'editorial',
      name: 'Editorial Teams',
      shortName: 'Editorial',
      priorityTopics: {
        'Citation Spike': 98,
        'Precedent-Setting Judgment': 90,
        'Legislative Development': 72,
        'Judiciary Modernization': 64,
        'AI Regulation': 60,
      },
      priorityJurisdictions: coreJurisdictions,
      frequency: 'Weekly',
      channel: 'Email',
      tone: 'Editorial',
    },
  ];

  const intelligenceItems = [
    {
      id: 'li-001',
      title: 'Singapore consults on model governance expectations for high-impact AI systems',
      source: 'IMDA / AI Verify',
      jurisdiction: 'Singapore',
      date: '2026-05-24',
      topic: 'AI Regulation',
      summary: 'Regulators are signalling stronger explainability, audit trail and accountability expectations for AI systems used in professional services.',
      urgency: 'STRATEGIC',
      impactScore: 91,
      status: 'New',
      tags: ['legal_ai', 'ai_governance', 'product_risk'],
    },
    {
      id: 'li-002',
      title: 'Hong Kong courts expand pilot guidance for electronic bundles and remote hearings',
      source: 'Hong Kong Judiciary',
      jurisdiction: 'Hong Kong',
      date: '2026-05-23',
      topic: 'Judiciary Modernization',
      summary: 'Court administration updates indicate broader acceptance of structured electronic filing, remote hearing workflows and digital case papers.',
      urgency: 'WATCH',
      impactScore: 68,
      status: 'Reviewed',
      tags: ['courts', 'workflow', 'digitization'],
    },
    {
      id: 'li-003',
      title: 'India publishes draft rules touching automated decision transparency',
      source: 'Ministry of Electronics and Information Technology',
      jurisdiction: 'India',
      date: '2026-05-23',
      topic: 'AI Regulation',
      summary: 'Draft policy language points to disclosure, human oversight and accountability obligations for automated systems in regulated sectors.',
      urgency: 'ACTION REQUIRED',
      impactScore: 94,
      status: 'New',
      tags: ['ai_regulation', 'consultation', 'india'],
    },
    {
      id: 'li-004',
      title: 'Australia privacy reform package progresses with new data minimisation obligations',
      source: 'OAIC / Federal Register',
      jurisdiction: 'Australia',
      date: '2026-05-22',
      topic: 'Privacy/Data Protection',
      summary: 'Proposed amendments would sharpen consent, retention and data minimisation expectations for digital services and analytics products.',
      urgency: 'ACTION REQUIRED',
      impactScore: 88,
      status: 'Reviewed',
      tags: ['privacy', 'data_governance', 'compliance'],
    },
    {
      id: 'li-005',
      title: 'Malaysia parliamentary committee schedules hearings on online safety legislation',
      source: 'Parliament of Malaysia',
      jurisdiction: 'Malaysia',
      date: '2026-05-21',
      topic: 'Legislative Development',
      summary: 'Committee calendar indicates near-term scrutiny of platform duties, content moderation thresholds and digital enforcement powers.',
      urgency: 'STRATEGIC',
      impactScore: 79,
      status: 'New',
      tags: ['legislation', 'online_safety', 'platforms'],
    },
    {
      id: 'li-006',
      title: 'Singapore legal AI vendor launches contract review benchmark for enterprise buyers',
      source: 'Legal Tech Market Scan',
      jurisdiction: 'Singapore',
      date: '2026-05-20',
      topic: 'Legal Tech Market Intelligence',
      summary: 'The launch packages benchmark reporting, clause risk scoring and procurement-ready assurance materials for in-house legal teams.',
      urgency: 'STRATEGIC',
      impactScore: 82,
      status: 'Reviewed',
      tags: ['competitor', 'legal_ai', 'sales_enablement'],
    },
    {
      id: 'li-007',
      title: 'India Supreme Court ruling clarifies platform liability in user-generated content claims',
      source: 'Supreme Court of India',
      jurisdiction: 'India',
      date: '2026-05-19',
      topic: 'Precedent-Setting Judgment',
      summary: 'The judgment narrows when intermediaries can rely on safe-harbour protections after notice and repeated non-compliance allegations.',
      urgency: 'ACTION REQUIRED',
      impactScore: 90,
      status: 'Approved',
      tags: ['judgment', 'platform_liability', 'editorial'],
    },
    {
      id: 'li-008',
      title: 'Australia court analytics provider adds generative search over tribunal decisions',
      source: 'Legal Tech Market Scan',
      jurisdiction: 'Australia',
      date: '2026-05-18',
      topic: 'Legal Tech Market Intelligence',
      summary: 'The release combines semantic search, generated case summaries and citation path exploration for employment and migration tribunals.',
      urgency: 'WATCH',
      impactScore: 72,
      status: 'New',
      tags: ['competitor', 'legal_search', 'ai_summaries'],
    },
    {
      id: 'li-009',
      title: 'Hong Kong privacy commissioner issues guidance on employee monitoring technologies',
      source: 'PCPD Hong Kong',
      jurisdiction: 'Hong Kong',
      date: '2026-05-17',
      topic: 'Privacy/Data Protection',
      summary: 'Guidance highlights transparency, proportionality and retention controls for workplace analytics, device monitoring and biometric systems.',
      urgency: 'WATCH',
      impactScore: 69,
      status: 'Reviewed',
      tags: ['privacy', 'employment', 'guidance'],
    },
    {
      id: 'li-010',
      title: 'Malaysia courts publish expanded taxonomy for judgment metadata',
      source: 'Office of the Chief Registrar',
      jurisdiction: 'Malaysia',
      date: '2026-05-16',
      topic: 'Judiciary Modernization',
      summary: 'The taxonomy adds metadata for case type, procedural posture and appellate outcome, improving structured research and editorial workflows.',
      urgency: 'INFORMATIONAL',
      impactScore: 58,
      status: 'Reviewed',
      tags: ['court_data', 'metadata', 'editorial'],
    },
    {
      id: 'li-011',
      title: 'Singapore consultation proposes mandatory incident logs for high-risk AI deployments',
      source: 'IMDA / AI Verify',
      jurisdiction: 'Singapore',
      date: '2026-05-15',
      topic: 'AI Regulation',
      summary: 'Consultation materials point to operational logging, incident tracking and post-deployment monitoring duties for high-risk AI tools.',
      urgency: 'ACTION REQUIRED',
      impactScore: 93,
      status: 'New',
      tags: ['ai_regulation', 'audit_trail', 'product_governance'],
    },
    {
      id: 'li-012',
      title: 'Hong Kong bill proposes structured access to legislative materials through official APIs',
      source: 'Legislation Desk',
      jurisdiction: 'Hong Kong',
      date: '2026-05-14',
      topic: 'API/Data Licensing',
      summary: 'The bill would authorise standardised API access for legislation, amendment history and commencement information.',
      urgency: 'STRATEGIC',
      impactScore: 86,
      status: 'New',
      tags: ['api', 'legislation', 'data_products'],
    },
    {
      id: 'li-013',
      title: 'Australia High Court decision reshapes implied terms analysis in platform contracts',
      source: 'High Court of Australia',
      jurisdiction: 'Australia',
      date: '2026-05-13',
      topic: 'Precedent-Setting Judgment',
      summary: 'The decision is expected to influence drafting, platform terms and commentary demand around digital contracting obligations.',
      urgency: 'STRATEGIC',
      impactScore: 81,
      status: 'Approved',
      tags: ['judgment', 'contracts', 'annotations'],
    },
    {
      id: 'li-014',
      title: 'Malaysia bar committee flags demand for explainers on AI evidence and hallucination risk',
      source: 'Malaysian Bar',
      jurisdiction: 'Malaysia',
      date: '2026-05-12',
      topic: 'AI Regulation',
      summary: 'Professional commentary points to growing demand for practical materials on AI-generated evidence, verification and professional responsibility.',
      urgency: 'INFORMATIONAL',
      impactScore: 61,
      status: 'New',
      tags: ['ai_ethics', 'editorial_signal', 'professional_responsibility'],
    },
    {
      id: 'li-015',
      title: 'India legal data provider revises API terms for citation graph access',
      source: 'Market Intelligence Desk',
      jurisdiction: 'India',
      date: '2026-05-11',
      topic: 'API/Data Licensing',
      summary: 'New API terms restrict bulk caching, require attribution and create premium tiers for citation graph and judgment enrichment endpoints.',
      urgency: 'STRATEGIC',
      impactScore: 87,
      status: 'New',
      tags: ['api', 'licensing', 'legal_data'],
    },
    {
      id: 'li-016',
      title: 'Singapore Law Watch reports citation spike around AI evidence admissibility note',
      source: 'Singapore Law Watch',
      jurisdiction: 'Singapore',
      date: '2026-05-10',
      topic: 'Citation Spike',
      summary: 'A recent note on AI-generated evidence is being cited across practitioner commentary and dispute-preparation materials.',
      urgency: 'WATCH',
      impactScore: 70,
      status: 'Reviewed',
      tags: ['citations', 'ai_evidence', 'editorial'],
    },
    {
      id: 'li-017',
      title: 'Hong Kong legal research platform launches AI-assisted Chinese-English case summarisation',
      source: 'Legal Tech Market Scan',
      jurisdiction: 'Hong Kong',
      date: '2026-05-09',
      topic: 'Legal Tech Market Intelligence',
      summary: 'A competitor release focuses on bilingual summarisation, citation extraction and law-firm workflow packaging.',
      urgency: 'WATCH',
      impactScore: 73,
      status: 'New',
      tags: ['competitor', 'bilingual_ai', 'case_summaries'],
    },
    {
      id: 'li-018',
      title: 'Australia introduces bill to strengthen automated decision accountability',
      source: 'Federal Register of Legislation',
      jurisdiction: 'Australia',
      date: '2026-05-08',
      topic: 'Legislative Development',
      summary: 'The bill would require agencies and regulated entities to document human review, automated decision logic and complaint pathways.',
      urgency: 'STRATEGIC',
      impactScore: 84,
      status: 'Reviewed',
      tags: ['legislation', 'automated_decisions', 'governance'],
    },
    {
      id: 'li-019',
      title: 'Malaysia data protection commissioner signals review of cross-border transfer guidance',
      source: 'Personal Data Protection Department',
      jurisdiction: 'Malaysia',
      date: '2026-05-07',
      topic: 'Privacy/Data Protection',
      summary: 'Statements indicate updated transfer guidance may clarify adequacy, contract safeguards and vendor-risk documentation.',
      urgency: 'WATCH',
      impactScore: 66,
      status: 'Reviewed',
      tags: ['privacy', 'cross_border_data', 'guidance'],
    },
    {
      id: 'li-020',
      title: 'India eCourts programme publishes roadmap for searchable order metadata',
      source: 'eCourts Mission Mode Project',
      jurisdiction: 'India',
      date: '2026-05-06',
      topic: 'Judiciary Modernization',
      summary: 'Roadmap materials describe richer order metadata, searchable hearing records and structured access for court information services.',
      urgency: 'INFORMATIONAL',
      impactScore: 63,
      status: 'Reviewed',
      tags: ['ecourts', 'metadata', 'court_modernization'],
    },
  ];

  return { coreJurisdictions, topics, sourceRegistry, departments, intelligenceItems };
})();
