from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Literal


BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: tuple[str, ...]) -> tuple[str, ...]:
    value = os.getenv(name)
    if not value:
        return default
    return tuple(part.strip() for part in value.split(",") if part.strip())


@dataclass(frozen=True)
class Settings:
    database_path: Path = Path(os.getenv("LEGAL_UPDATES_DB_PATH", DATA_DIR / "legal_updates.db"))
    enable_scheduler: bool = env_bool("LEGAL_UPDATES_ENABLE_SCHEDULER", True)
    run_on_start: bool = env_bool("LEGAL_UPDATES_RUN_ON_START", False)
    daily_run_hour: int = int(os.getenv("LEGAL_UPDATES_DAILY_RUN_HOUR", "6"))
    source_timeout_seconds: float = float(os.getenv("LEGAL_UPDATES_SOURCE_TIMEOUT", "18"))
    source_limit_per_run: int = int(os.getenv("LEGAL_UPDATES_SOURCE_LIMIT", "25"))
    ai_summary_provider: str = os.getenv("AI_SUMMARY_PROVIDER", "auto")
    openai_api_key: str = os.getenv("OPENAI_API_KEY", "")
    openai_summary_model: str = os.getenv("OPENAI_SUMMARY_MODEL", "gpt-5.4-nano")
    openai_timeout_seconds: float = float(os.getenv("OPENAI_TIMEOUT_SECONDS", "30"))
    local_ai_base_url: str = os.getenv("LOCAL_AI_BASE_URL", "http://127.0.0.1:11434")
    local_ai_model: str = os.getenv("LOCAL_AI_MODEL", "llama3.2:1b")
    public_mode: bool = env_bool("LEGAL_UPDATES_PUBLIC_MODE", False)
    github_pages_origin: str = os.getenv("GITHUB_PAGES_ORIGIN", "https://YOUR-GITHUB-USERNAME.github.io")
    cors_origins: tuple[str, ...] = env_list(
        "LEGAL_UPDATES_CORS_ORIGINS",
        (
            "http://localhost:5174",
            "http://127.0.0.1:5174",
            "http://localhost:8000",
            "http://127.0.0.1:8000",
            "https://YOUR-GITHUB-USERNAME.github.io",
        ),
    )
    user_agent: str = os.getenv(
        "LEGAL_UPDATES_USER_AGENT",
        "APACLegalUpdatesRadar/0.1 (+local legal monitoring dashboard)",
    )


settings = Settings()


Country = Literal["Malaysia", "Singapore", "Hong Kong", "Australia", "New Zealand", "India"]
SourceType = Literal["rss", "html"]
LegalAiIngestionMethod = Literal["rss", "api", "scraper", "manual", "pending"]

PRIMARY_CATEGORIES = [
    "Press Release/Judiciary Updates",
    "Case Summary",
    "Recent Judgments",
    "Policy/Regulatory News",
    "Legal News",
    "Legislation News",
]

RETIRED_SOURCE_IDS = {
    "au_federal_court",
    "hk_gov_law_order_rss",
    "hk_scmp_law_crime",
    "my_malaymail_malaysia",
    "my_thestar_nation",
    "sg_cna_singapore",
}

RETIRED_SOURCE_NAMES = {
    "Federal Court of Australia",
    "news.gov.hk - Law & Order RSS",
    "SCMP - Hong Kong Law and Crime",
    "Malay Mail - Malaysia",
    "CNA - Singapore",
    "The Star - Nation",
    "The Star - Nation RSS",
}

JUDICIARY_NEWS_TERMS = (
    "attorney-general",
    "chief justice",
    "court",
    "court of appeal",
    "court ruling",
    "court rules",
    "courts",
    "high court",
    "judge",
    "judges",
    "judicial",
    "judiciary",
    "judgment",
    "judgement",
    "law reform",
    "lawyer",
    "lawyers",
    "legal profession",
    "legal service",
    "legal services",
    "legislation",
    "legislative",
    "state courts",
    "supreme court",
)

GENERAL_ENFORCEMENT_BLOCKLIST = (
    "accused of importing",
    "arrested",
    "caning",
    "drug",
    "feeding",
    "jailed for",
    "jail for",
    "police raid",
)


@dataclass(frozen=True)
class Source:
    id: str
    country: str
    name: str
    url: str
    source_type: SourceType
    category: str = "Legal News"
    official: bool = False
    include_all: bool = False
    source_tab: str | None = None
    country_detection: bool = False
    force_category: bool = False
    item_selector: str | None = None
    title_selector: str | None = None
    link_selector: str | None = None
    summary_selector: str | None = None
    date_selector: str | None = None
    require_date: bool = False
    required_terms: tuple[str, ...] = ()
    excluded_terms: tuple[str, ...] = ()


@dataclass(frozen=True)
class LegalAiNewsSource:
    id: str
    name: str
    url: str
    category: str
    source_type: str
    region: str
    tags: tuple[str, ...]
    ingestion_method: LegalAiIngestionMethod
    notes: str
    content_group: str = "legal_ai_news"


COUNTRIES: list[Country] = ["Malaysia", "Singapore", "Hong Kong", "Australia", "New Zealand", "India"]

COUNTRY_SIGNALS: dict[str, tuple[str, ...]] = {
    "Malaysia": ("malaysia", "malaysian", "kuala lumpur", "putrajaya", "malaysian bar"),
    "Singapore": ("singapore", "singaporean", "ministry of law", "state courts", "elitigation"),
    "Hong Kong": ("hong kong", "hk", "hksar", "hkba", "hkiac"),
    "Australia": ("australia", "australian", "high court of australia", "asic", "sydney", "melbourne"),
    "New Zealand": ("new zealand", "nz", "auckland", "wellington", "law society news"),
    "India": ("india", "indian", "new delhi", "supreme court of india", "sebi", "rbi", "meity", "ibbi"),
}

LEGAL_KEYWORDS = {
    "appeals court",
    "apex court",
    "arbitration",
    "attorney-general",
    "bar association",
    "bar council",
    "bill",
    "case summary",
    "civil suit",
    "chief justice",
    "constitutional",
    "court",
    "court of appeal",
    "courts",
    "court ruling",
    "doj",
    "federal court",
    "grounds of decision",
    "hearing",
    "high court",
    "judicial",
    "judicial review",
    "judiciary",
    "judge",
    "judges",
    "judgment",
    "judgement",
    "law council",
    "law reform",
    "law society",
    "lawsuit",
    "legal action",
    "legal aid",
    "legal challenge",
    "legal counsel",
    "legal practice",
    "legal proceedings",
    "legal profession",
    "legal services",
    "legislation",
    "legislative",
    "leave to appeal",
    "litigation",
    "magistrate",
    "practice direction",
    "public prosecutor",
    "prosecution",
    "patent infringement",
    "circular",
    "notification",
    "regulation",
    "regulatory",
    "rules of court",
    "solicitor",
    "statute",
    "supreme court",
    "trial",
    "tribunal",
    "acquitted",
    "convicted",
    "conviction",
    "sentence",
    "sentencing",
    "mahkamah",
    "hakim",
    "kehakiman",
    "pendakwa",
    "perbicaraan",
    "penghakiman",
}

LAW_ENFORCEMENT_NOISE = {
    "arrest",
    "arrested",
    "cops",
    "crime",
    "criminal record",
    "detained",
    "drug bust",
    "investigation",
    "law enforcement",
    "police",
    "police chief",
    "raid",
    "seized",
    "suspect",
    "suspects",
    "syndicate",
}

CATEGORY_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("Legislation News", ("bill", "act", "regulation", "amendment", "law reform", "legislative", "parliament", "statute")),
    ("Policy/Regulatory News", ("policy", "policies", "regulatory", "regulator", "monetary authority", "mas", "insurance association", "guidelines", "consultation paper")),
    ("Case Summary", ("case summary", "press summary", "summary review", "grounds of decision")),
    ("Press Release/Judiciary Updates", ("press release", "media release", "media advisory", "chief justice", "judicial appointment", "judge appointed", "practice direction", "registrar's circular", "registrar circular", "court circular", "rules of court")),
]


LEGACY_SOURCES: list[Source] = [
    Source(
        id="my_judiciary_press",
        country="Malaysia",
        name="Malaysian Judiciary Press Releases",
        url="https://www.kehakiman.gov.my/en/public-access/media/press-release",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector=".panel-body li",
    ),
    Source(
        id="my_fmt_nation",
        country="Malaysia",
        name="Free Malaysia Today - Nation",
        url="https://www.freemalaysiatoday.com/category/nation/feed/",
        source_type="rss",
    ),
    Source(
        id="my_bernama_crime_courts",
        country="Malaysia",
        name="Bernama RSS",
        url="https://www.bernama.com/en/index.php/rssfeed.php",
        source_type="rss",
        category="Court News/Legal News",
    ),
    Source(
        id="sg_judiciary_news",
        country="Singapore",
        name="Singapore Courts News and Speeches",
        url="https://www.judiciary.gov.sg/news-and-resources/news",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="a.list-item",
        title_selector="h4",
        summary_selector=".synopsis",
        require_date=True,
    ),
    Source(
        id="sg_judiciary_judgments",
        country="Singapore",
        name="Singapore Courts Judgments - eLitigation",
        url="https://www.elitigation.sg/gd",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector=".card-body.gd",
        title_selector="a.gd-heardertext",
        link_selector="a.gd-heardertext",
        summary_selector=".align-items-center",
        date_selector="a.decision-date-link",
        require_date=True,
    ),
    Source(
        id="sg_lawwatch_headlines",
        country="Singapore",
        name="Singapore Law Watch Headlines",
        url="https://www.singaporelawwatch.sg/Headlines",
        source_type="html",
        category="Court News/Legal News",
        include_all=True,
        item_selector="article, .item, .media, li",
        require_date=True,
    ),
    Source(
        id="sg_cna_judiciary",
        country="Singapore",
        name="CNA - Singapore Judiciary Filter",
        url="https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416",
        source_type="rss",
        required_terms=JUDICIARY_NEWS_TERMS,
        excluded_terms=GENERAL_ENFORCEMENT_BLOCKLIST,
    ),
    Source(
        id="sg_conventus",
        country="Singapore",
        name="Conventus Law - Singapore RSS",
        url="https://conventuslaw.com/tag/singapore/feed/",
        source_type="rss",
        category="Court News/Legal News",
    ),
    Source(
        id="hk_judiciary_press",
        country="Hong Kong",
        name="Hong Kong Judiciary Press Releases",
        url="https://www.judiciary.hk/en/other_information/press_rel/press_rel_2026.html",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="li",
        link_selector="a[href]",
        require_date=True,
    ),
    Source(
        id="hk_doj_notable_jr",
        country="Hong Kong",
        name="Hong Kong DoJ Notable Judgments - Judicial Review",
        url="https://www.doj.gov.hk/en/notable_judgments/summary_review_cases.html",
        source_type="html",
        category="Case Summary",
        official=True,
        include_all=True,
        item_selector="table tr",
        require_date=True,
    ),
    Source(
        id="hk_doj_notable_civil",
        country="Hong Kong",
        name="Hong Kong DoJ Notable Judgments - Civil",
        url="https://www.doj.gov.hk/en/notable_judgments/summary_civil_cases.html",
        source_type="html",
        category="Case Summary",
        official=True,
        include_all=True,
        item_selector="table tr",
        require_date=True,
    ),
    Source(
        id="hk_court_news",
        country="Hong Kong",
        name="HK Court News RSS",
        url="https://hkcourtnews.com/feed/",
        source_type="rss",
        category="Court News/Legal News",
        include_all=True,
    ),
    Source(
        id="au_high_court_judgments",
        country="Australia",
        name="High Court of Australia Judgments",
        url="https://www.hcourt.gov.au/cases-and-judgments/judgments/judgments-1998-current",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .search-result, li",
        require_date=True,
    ),
    Source(
        id="au_high_court_news",
        country="Australia",
        name="High Court of Australia News",
        url="https://www.hcourt.gov.au/news",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .news, li",
        require_date=True,
    ),
    Source(
        id="au_law_council_media",
        country="Australia",
        name="Law Council of Australia - Media Releases",
        url="https://lawcouncil.au/media/media-releases",
        source_type="html",
        category="Court News/Legal News",
        include_all=True,
        item_selector="article, .item, .search-result, li",
        require_date=True,
    ),
    Source(
        id="nz_courts_home",
        country="New Zealand",
        name="Courts of New Zealand Latest Updates",
        url="https://www.courtsofnz.govt.nz/",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector="article, .card, .latest-updates li, li",
        require_date=True,
    ),
    Source(
        id="nz_courts_judgments",
        country="New Zealand",
        name="Courts of New Zealand Judgments",
        url="https://www.courtsofnz.govt.nz/judgments",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector="article, .card, li",
        require_date=True,
    ),
    Source(
        id="nz_district_court_news",
        country="New Zealand",
        name="District Court of New Zealand News",
        url="https://www.districtcourts.govt.nz/",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="article, .card, .news-list li, li",
        require_date=True,
    ),
    Source(
        id="nz_law_society_news",
        country="New Zealand",
        name="New Zealand Law Society News",
        url="https://www.lawsociety.org.nz/news/",
        source_type="html",
        category="Court News/Legal News",
        item_selector="article, .card, .teaser, li",
        require_date=True,
    ),
]


LEGAL_AI_NEWS_SOURCES: list[LegalAiNewsSource] = [
    LegalAiNewsSource(
        id="ai_artificial_lawyer",
        name="Artificial Lawyer",
        url="https://www.artificiallawyer.com/",
        category="Editorial",
        source_type="editorial/legal_ai_news",
        region="global",
        tags=("legal_ai", "legal_tech", "legal_market"),
        ingestion_method="rss",
        notes="Legal AI, legal tech product launches, industry commentary.",
    ),
    LegalAiNewsSource(
        id="ai_lawsites",
        name="LawSites by Bob Ambrogi",
        url="https://www.lawnext.com/",
        category="Editorial",
        source_type="editorial/legal_tech_analysis",
        region="us",
        tags=("legal_ai", "legal_tech", "legal_market"),
        ingestion_method="rss",
        notes="Legal technology, AI tools, legal market analysis.",
    ),
    LegalAiNewsSource(
        id="ai_legaltech_news",
        name="Legaltech News",
        url="https://www.law.com/legaltechnews/",
        category="Editorial",
        source_type="editorial/legal_tech_news",
        region="us",
        tags=("legal_ai", "legal_tech", "legal_market"),
        ingestion_method="scraper",
        notes="Legal tech and AI adoption by firms and legal departments.",
    ),
    LegalAiNewsSource(
        id="ai_aba_legal_technology",
        name="ABA Journal Legal Technology",
        url="https://www.abajournal.com/topic/legal+technology",
        category="Editorial",
        source_type="editorial/legal_profession_tech",
        region="us",
        tags=("legal_tech", "ai_ethics", "legal_market"),
        ingestion_method="scraper",
        notes="Legal profession technology and AI ethics developments.",
    ),
    LegalAiNewsSource(
        id="ai_thomson_reuters_institute",
        name="Thomson Reuters Institute",
        url="https://www.thomsonreuters.com/en-us/posts/",
        category="Market Intelligence",
        source_type="market_intelligence",
        region="global",
        tags=("legal_ai", "legal_market", "competitor_intelligence"),
        ingestion_method="scraper",
        notes="Legal market, professional services, AI adoption and productivity.",
    ),
    LegalAiNewsSource(
        id="ai_oecd_policy_observatory",
        name="OECD AI Policy Observatory",
        url="https://oecd.ai/",
        category="Official",
        source_type="official/ai_policy",
        region="global",
        tags=("ai_regulation", "ai_governance", "ai_ethics"),
        ingestion_method="manual",
        notes="Global AI policy database, national AI strategies, AI governance.",
    ),
    LegalAiNewsSource(
        id="ai_stanford_hai_index",
        name="Stanford HAI AI Index",
        url="https://hai.stanford.edu/ai-index",
        category="Research",
        source_type="research/ai_policy",
        region="global",
        tags=("ai_regulation", "ai_governance", "legal_market"),
        ingestion_method="manual",
        notes="Global AI research, adoption, policy, governance, and industry trends.",
    ),
    LegalAiNewsSource(
        id="ai_eu_ai_act",
        name="EU Artificial Intelligence Act",
        url="https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
        category="Official",
        source_type="official/ai_regulation",
        region="eu",
        tags=("ai_regulation", "ai_governance", "ai_ethics"),
        ingestion_method="manual",
        notes="EU AI Act and regulatory framework updates.",
    ),
    LegalAiNewsSource(
        id="ai_uk_dsit",
        name="UK AI Regulation / DSIT",
        url="https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology",
        category="Official",
        source_type="official/ai_policy",
        region="uk",
        tags=("ai_regulation", "ai_governance", "ai_ethics"),
        ingestion_method="manual",
        notes="UK AI governance and regulatory developments.",
    ),
    LegalAiNewsSource(
        id="ai_sg_imda",
        name="Singapore IMDA AI Verify",
        url="https://www.imda.gov.sg/",
        category="Official",
        source_type="official/apac_ai_governance",
        region="singapore",
        tags=("ai_governance", "ai_regulation", "legal_ai"),
        ingestion_method="manual",
        notes="Singapore AI governance, AI Verify, and trusted AI frameworks.",
    ),
    LegalAiNewsSource(
        id="ai_verify_foundation",
        name="AI Verify Foundation",
        url="https://aiverifyfoundation.sg/",
        category="Official",
        source_type="official/apac_ai_governance",
        region="apac",
        tags=("ai_governance", "ai_ethics", "legal_ai"),
        ingestion_method="manual",
        notes="AI testing, governance, assurance, and open-source AI safety tooling.",
    ),
    LegalAiNewsSource(
        id="ai_openai_news",
        name="OpenAI News",
        url="https://openai.com/news/",
        category="Vendor",
        source_type="vendor/ai_platform",
        region="global",
        tags=("legal_ai", "competitor_intelligence", "legal_tech"),
        ingestion_method="scraper",
        notes="AI model and platform developments relevant to legal AI products.",
    ),
    LegalAiNewsSource(
        id="ai_harvey",
        name="Harvey",
        url="https://www.harvey.ai/",
        category="Vendor",
        source_type="vendor/legal_ai",
        region="global",
        tags=("legal_ai", "legal_tech", "competitor_intelligence"),
        ingestion_method="manual",
        notes="Legal AI assistant and enterprise legal AI developments.",
    ),
    LegalAiNewsSource(
        id="ai_vlex",
        name="vLex",
        url="https://vlex.com/",
        category="Vendor",
        source_type="vendor/legal_ai",
        region="global",
        tags=("legal_ai", "legal_tech", "competitor_intelligence"),
        ingestion_method="manual",
        notes="Legal research AI and legal intelligence developments.",
    ),
    LegalAiNewsSource(
        id="ai_clio_blog",
        name="Clio Blog",
        url="https://www.clio.com/blog/",
        category="Vendor",
        source_type="vendor/legal_tech",
        region="us",
        tags=("legal_ai", "legal_tech", "legal_market"),
        ingestion_method="scraper",
        notes="Legal practice technology and AI adoption.",
    ),
]


SOURCES: list[Source] = [
    Source(
        id="my_judiciary_press",
        country="Malaysia",
        name="Malaysian Judiciary Press Releases",
        url="https://www.kehakiman.gov.my/en/public-access/media/press-release",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector=".panel-body li",
    ),
    Source(
        id="my_lom_whats_new",
        country="Malaysia",
        name="Laws of Malaysia - What's New",
        url="https://lom.agc.gov.my/index.php",
        source_type="html",
        category="Legislation News",
        source_tab="Laws of Malaysia",
        official=True,
        include_all=True,
        force_category=True,
        require_date=True,
    ),
    Source(
        id="my_fmt_nation",
        country="Malaysia",
        name="Free Malaysia Today - Nation",
        url="https://www.freemalaysiatoday.com/category/nation/feed/",
        source_type="rss",
        category="Legal News",
        source_tab="News Sources",
    ),
    Source(
        id="my_bar_legal_news",
        country="Malaysia",
        name="Malaysian Bar - Legal News",
        url="https://www.malaysianbar.org.my/list/news/legal-and-general-news/legal-news",
        source_type="html",
        category="Legal News",
        source_tab="Malaysian Bar",
        include_all=True,
        item_selector="ul.list-home > li",
        title_selector="p",
        link_selector="a[href]",
        summary_selector="p",
        date_selector=".greytxt",
        require_date=True,
    ),
    Source(
        id="my_bar_bar_news",
        country="Malaysia",
        name="Malaysian Bar - Bar News",
        url="https://www.malaysianbar.org.my/list/news/bar-news/news",
        source_type="html",
        category="Legal News",
        source_tab="Malaysian Bar",
        include_all=True,
        item_selector="ul.list-home > li",
        title_selector="p",
        link_selector="a[href]",
        summary_selector="p",
        date_selector=".greytxt",
        require_date=True,
    ),
    Source(
        id="my_bar_appellate_courts",
        country="Malaysia",
        name="Malaysian Bar - Appellate Courts Highlights",
        url="https://www.malaysianbar.org.my/list/news/highlights-from-the-appellate-courts/highlights-from-the-appellate-courts",
        source_type="html",
        category="Legal News",
        source_tab="Malaysian Bar",
        include_all=True,
        item_selector="ul.list-home > li",
        title_selector="p",
        link_selector="a[href]",
        summary_selector="p",
        date_selector=".greytxt",
        require_date=True,
    ),
    Source(
        id="my_bar_notices",
        country="Malaysia",
        name="Malaysian Bar - Notices",
        url="https://www.malaysianbar.org.my/list/news/bar-news/notices",
        source_type="html",
        category="Press Release/Judiciary Updates",
        source_tab="Malaysian Bar",
        include_all=True,
        item_selector="ul.list-home > li",
        title_selector="p",
        link_selector="a[href]",
        summary_selector="p",
        date_selector=".greytxt",
        require_date=True,
    ),
    Source(
        id="my_malaysiakini",
        country="Malaysia",
        name="Malaysiakini",
        url="https://www.malaysiakini.com",
        source_type="html",
        category="Legal News",
        source_tab="News Sources",
        item_selector="article, .uk-card, .media, li",
    ),
    Source(
        id="my_bernama_crime_courts",
        country="Malaysia",
        name="Bernama RSS",
        url="https://www.bernama.com/en/index.php/rssfeed.php",
        source_type="rss",
        category="Legal News",
        source_tab="News Sources",
    ),
    Source(
        id="sg_judiciary_news",
        country="Singapore",
        name="Singapore Courts News and Speeches",
        url="https://www.judiciary.gov.sg/news-and-resources/news",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="a.list-item",
        title_selector="h4",
        summary_selector=".synopsis",
        require_date=True,
    ),
    Source(
        id="sg_judiciary_judgments",
        country="Singapore",
        name="Singapore Courts Judgments - eLitigation",
        url="https://www.elitigation.sg/gd",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector=".card-body.gd",
        title_selector="a.gd-heardertext",
        link_selector="a.gd-heardertext",
        summary_selector=".align-items-center",
        date_selector="a.decision-date-link",
        require_date=True,
    ),
    Source(
        id="sg_lawwatch_headlines",
        country="Singapore",
        name="Singapore Law Watch Headlines",
        url="https://www.singaporelawwatch.sg/Headlines",
        source_type="html",
        category="Legal News",
        source_tab="News Sources",
        include_all=True,
        item_selector="article, .item, .media, li",
        require_date=True,
    ),
    Source(
        id="sg_cna_judiciary",
        country="Singapore",
        name="CNA - Singapore Judiciary Filter",
        url="https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416",
        source_type="rss",
        category="Legal News",
        source_tab="News Sources",
        force_category=True,
        required_terms=JUDICIARY_NEWS_TERMS,
        excluded_terms=GENERAL_ENFORCEMENT_BLOCKLIST,
    ),
    Source(
        id="sg_conventus",
        country="Singapore",
        name="Conventus Law - Singapore RSS",
        url="https://conventuslaw.com/tag/singapore/feed/",
        source_type="rss",
        category="Legal News",
        source_tab="News Sources",
    ),
    Source(
        id="sg_minlaw_news",
        country="Singapore",
        name="Singapore Ministry of Law News",
        url="https://www.mlaw.gov.sg/news",
        source_type="html",
        category="Press Release/Judiciary Updates",
        source_tab="Ministry of Law",
        official=True,
        include_all=True,
        item_selector="article, .card, .list-item, li",
    ),
    Source(
        id="sg_sso_new_legislation",
        country="Singapore",
        name="Singapore Statutes Online - New Legislation",
        url="https://sso.agc.gov.sg/What's-New/New-Legislation/RSS",
        source_type="rss",
        category="Legislation News",
        source_tab="Singapore Statutes Online",
        official=True,
        include_all=True,
        force_category=True,
    ),
    Source(
        id="hk_judiciary_press",
        country="Hong Kong",
        name="Hong Kong Judiciary Press Releases",
        url="https://www.judiciary.hk/en/other_information/press_rel/press_rel_2026.html",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="li",
        link_selector="a[href]",
        require_date=True,
    ),
    Source(
        id="hk_bar_events_publication",
        country="Hong Kong",
        name="Hong Kong Bar Association Events and Publications",
        url="https://www.hkba.org/events-publication",
        source_type="html",
        category="Legal News",
        source_tab="HKBA",
        include_all=True,
        item_selector="article, .views-row, .item, li",
    ),
    Source(
        id="hk_doj_notable_jr",
        country="Hong Kong",
        name="Hong Kong DoJ Notable Judgments - Judicial Review",
        url="https://www.doj.gov.hk/en/notable_judgments/summary_review_cases.html",
        source_type="html",
        category="Case Summary",
        source_tab="DoJ",
        official=True,
        include_all=True,
        item_selector="table tr",
        require_date=True,
    ),
    Source(
        id="hk_doj_notable_civil",
        country="Hong Kong",
        name="Hong Kong DoJ Notable Judgments - Civil",
        url="https://www.doj.gov.hk/en/notable_judgments/summary_civil_cases.html",
        source_type="html",
        category="Case Summary",
        source_tab="DoJ",
        official=True,
        include_all=True,
        item_selector="table tr",
        require_date=True,
    ),
    Source(
        id="hk_court_news",
        country="Hong Kong",
        name="HK Court News RSS",
        url="https://hkcourtnews.com/feed/",
        source_type="rss",
        category="Legal News",
        source_tab="News Sources",
        include_all=True,
    ),
    Source(
        id="au_high_court_judgments",
        country="Australia",
        name="High Court of Australia Judgments",
        url="https://www.hcourt.gov.au/cases-and-judgments/judgments/judgments-1998-current",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .search-result, li",
        require_date=True,
    ),
    Source(
        id="au_high_court_case_summaries",
        country="Australia",
        name="High Court of Australia Case Summaries",
        url="https://www.hcourt.gov.au/cases-and-judgments/hearings/case-summaries?f%5B0%5D=Y%3A2026",
        source_type="html",
        category="Case Summary",
        source_tab="AU HC",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .search-result, li",
        require_date=True,
    ),
    Source(
        id="au_high_court_news",
        country="Australia",
        name="High Court of Australia News",
        url="https://www.hcourt.gov.au/news",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .news, li",
        require_date=True,
    ),
    Source(
        id="au_law_council_media",
        country="Australia",
        name="Law Council of Australia - Media Releases",
        url="https://lawcouncil.au/media/media-releases",
        source_type="html",
        category="Legal News",
        source_tab="AU Law Council",
        include_all=True,
        item_selector="article, .item, .search-result, li",
        require_date=True,
    ),
    Source(
        id="nz_courts_home",
        country="New Zealand",
        name="Courts of New Zealand Latest Updates",
        url="https://www.courtsofnz.govt.nz/",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector="article, .card, .latest-updates li, li",
        require_date=True,
    ),
    Source(
        id="nz_courts_judgments",
        country="New Zealand",
        name="Courts of New Zealand Judgments",
        url="https://www.courtsofnz.govt.nz/judgments",
        source_type="html",
        category="Recent Judgments",
        official=True,
        include_all=True,
        item_selector="article, .card, li",
        require_date=True,
    ),
    Source(
        id="nz_district_court_news",
        country="New Zealand",
        name="District Court of New Zealand News",
        url="https://www.districtcourts.govt.nz/",
        source_type="html",
        category="Press Release/Judiciary Updates",
        official=True,
        include_all=True,
        item_selector="article, .card, .news-list li, li",
        require_date=True,
    ),
    Source(
        id="nz_law_society_news",
        country="New Zealand",
        name="New Zealand Law Society News",
        url="https://www.lawsociety.org.nz/news/",
        source_type="html",
        category="Legal News",
        item_selector="article, .card, .teaser, li",
        require_date=True,
    ),
    Source(
        id="in_lawmin_press",
        country="India",
        name="Ministry of Law & Justice Press Releases",
        url="https://lawmin.gov.in/press-release",
        source_type="html",
        category="Press Release/Judiciary Updates",
        source_tab="Ministry of Law & Justice",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .field-content, li",
        require_date=True,
    ),
    Source(
        id="in_india_code",
        country="India",
        name="India Code",
        url="https://www.indiacode.nic.in/",
        source_type="html",
        category="Legislation News",
        source_tab="India Code",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .card, li",
        require_date=True,
    ),
    Source(
        id="in_gazette",
        country="India",
        name="Gazette of India",
        url="https://egazette.gov.in/",
        source_type="html",
        category="Legislation News",
        source_tab="Gazette of India",
        official=True,
        include_all=True,
        item_selector="article, .item, .card, li, tr",
        require_date=True,
    ),
    Source(
        id="in_prs_legislative_research",
        country="India",
        name="PRS Legislative Research",
        url="https://prsindia.org/billtrack",
        source_type="html",
        category="Legislation News",
        source_tab="PRS",
        include_all=True,
        item_selector="article, .views-row, .card, li, tr",
        require_date=True,
    ),
    Source(
        id="in_supreme_court_judgments",
        country="India",
        name="Supreme Court of India",
        url="https://www.sci.gov.in/",
        source_type="html",
        category="Recent Judgments",
        source_tab="Supreme Court of India",
        official=True,
        include_all=True,
        item_selector="a[href]",
        require_date=True,
    ),
    Source(
        id="in_rbi_notifications",
        country="India",
        name="Reserve Bank of India Notifications",
        url="https://www.rbi.org.in/scripts/NotificationUser.aspx",
        source_type="html",
        category="Legislation News",
        source_tab="RBI",
        official=True,
        include_all=True,
        item_selector="article, .tablecontent1, .tablecontent2, li, tr",
        require_date=True,
    ),
    Source(
        id="in_sebi_rss",
        country="India",
        name="SEBI RSS Feed",
        url="https://www.sebi.gov.in/sebirss.xml",
        source_type="rss",
        category="Legislation News",
        source_tab="SEBI",
        official=True,
        include_all=True,
    ),
    Source(
        id="in_meity_notifications",
        country="India",
        name="MeitY Notifications",
        url="https://www.meity.gov.in/notifications",
        source_type="html",
        category="Legislation News",
        source_tab="MeitY",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .card, li, tr",
        require_date=True,
    ),
    Source(
        id="in_cci_press_releases",
        country="India",
        name="Competition Commission of India Press Releases",
        url="https://www.cci.gov.in/public/antitrust/press-release",
        source_type="html",
        category="Press Release/Judiciary Updates",
        source_tab="CCI",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .card, li, tr",
        require_date=True,
    ),
    Source(
        id="in_ibbi_updates",
        country="India",
        name="Insolvency and Bankruptcy Board of India Updates",
        url="https://ibbi.gov.in/",
        source_type="html",
        category="Legislation News",
        source_tab="IBBI",
        official=True,
        include_all=True,
        item_selector="article, .views-row, .card, li",
        require_date=True,
    ),
    Source(
        id="in_livelaw",
        country="India",
        name="LiveLaw",
        url="https://www.livelaw.in/",
        source_type="html",
        category="Legal News",
        source_tab="News Sources",
        item_selector="article, .post, .story, .card, li",
        require_date=True,
    ),
    Source(
        id="in_bar_and_bench",
        country="India",
        name="Bar & Bench",
        url="https://www.barandbench.com/",
        source_type="html",
        category="Legal News",
        source_tab="News Sources",
        item_selector="article, .post, .story, .card, li",
        require_date=True,
    ),
    Source(
        id="in_scc_online_blog",
        country="India",
        name="SCC Online Blog",
        url="https://www.scconline.com/blog/post/feed/",
        source_type="rss",
        category="Legal News",
        source_tab="News Sources",
    ),
    Source(
        id="asia_business_law_journal",
        country="Multiple",
        name="Asia Business Law Journal",
        url="https://law.asia/category/asia-business-law-journal",
        source_type="html",
        category="Legal News",
        source_tab="News Sources",
        country_detection=True,
        include_all=True,
        item_selector="article, .post, .type-post, li",
    ),
]
